# This workflow will run tests on push or PRs
name: CI

on:
  - push
  - pull_request

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install chromium --with-deps
      - name: Lint
        run: npm run lint
      - name: Unit tests
        run: npm run test:ci
      - name: Playwright e2e tests
        run: npm run test:browser:ci
      - name: Check build
        run: npm run build
      - name: Upload Playwright test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
